import 'package:FatCat/models/card_model.dart';

final List<CardModel> cards = [
  CardModel(
    id: "1",
    userId: "123",
    deckId: "1",
    question: "question",
    imageId: "imageId",
    answer: "answer",
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  CardModel(
    id: "2",
    userId: "123",
    deckId: "1",
    question: "question 2",
    imageId: "imageId 2",
    answer: "answer 2",
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  CardModel(
    id: "3",
    userId: "123",
    deckId: "1",
    question: "question 3",
    imageId: "imageId 3",
    answer: "answer 3",
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  CardModel(
    id: "4",
    userId: "123",
    deckId: "1",
    question: "question 4",
    imageId: "imageId 4",
    answer: "answer 4",
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
];

final List<CardModel> cardsForDeck1 = [
  CardModel(
    id: "1",
    userId: "123",
    deckId: "1",
    question: "question",
    imageId: "imageId",
    answer: "answer",
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  CardModel(
    id: "2",
    userId: "123",
    deckId: "1",
    question: "question 2",
    imageId: "imageId 2",
    answer: "answer 2",
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  CardModel(
    id: "3",
    userId: "123",
    deckId: "1",
    question: "question 3",
    imageId: "imageId 3",
    answer: "answer 3",
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  CardModel(
    id: "4",
    userId: "123",
    deckId: "1",
    question: "question 4",
    imageId: "imageId 4",
    answer: "answer 4",
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
];
final List<CardModel> cardsForDeck3 = [
  CardModel(
    id: "1",
    userId: "123",
    deckId: "1",
    question: "deck3 question 1",
    imageId: "imageId",
    answer: "answer",
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  CardModel(
    id: "2",
    userId: "123",
    deckId: "1",
    question: "question 2",
    imageId: "imageId 2",
    answer: "answer 2",
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  CardModel(
    id: "3",
    userId: "123",
    deckId: "1",
    question: "question 3",
    imageId: "imageId 3",
    answer: "answer 3",
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  CardModel(
    id: "4",
    userId: "123",
    deckId: "1",
    question: "question 4",
    imageId: "imageId 4",
    answer: "answer 4",
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
];
final List<CardModel> cardsForDeck2 = [
  CardModel(
    id: "1",
    userId: "123",
    deckId: "1",
    question: "deck2 question 1",
    imageId: "imageId",
    answer: "answer",
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  CardModel(
    id: "2",
    userId: "123",
    deckId: "1",
    question: "question 2",
    imageId: "imageId 2",
    answer: "answer 2",
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  CardModel(
    id: "3",
    userId: "123",
    deckId: "1",
    question: "question 3",
    imageId: "imageId 3",
    answer: "answer 3",
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  CardModel(
    id: "4",
    userId: "123",
    deckId: "1",
    question: "question 4",
    imageId: "imageId 4",
    answer: "answer 4",
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
];

Map<String, List<CardModel>> cardsForDecks = {
  "1": cardsForDeck1,
  "2": cardsForDeck2,
  "3": cardsForDeck3,
};
